### ISSUE TITLE
Feature request: exlude region for next print in queue

### ISSUE THREAD

**Issue by maukcc** [bradcfisher/OctoPrint-ExcludeRegionPlugin#12]
So you are printing a small part and the rest of the bed is empty. You queue the next printjob (which your slicer also placed in the middle of the bed) and you want it to start automatically after the current print is done. But not in the middle of the bed as there is already an other part printed there.

Would it be possible to exclude the region the current printjob is using, and start the next job automatically somewhere else?

**Comment by bradcfisher** [comment]
That's a very interesting idea.

From a gcode processing perspective, it should definitely be possible to relocate a print to a new region of the bed, and that process could actually be implemented similarly to how the exclude region plugin currently tracks the effective coordinates while excluding from within a specific region.  Essentially, it could be a simple transformation applied to all the bed coordinates in the gcode to map them to a specific region of the print bed.  One could also automatically apply appropriate automatic exclude regions as a failsafe to ensure the relocated print doesn't try to print outside the physical boundaries of the printer.

From a UI perspective, though, it seems like it would be a large undertaking.  Essentially, an interface to define and manage a queue of jobs would need to be implemented, and appropriate exclude regions (or coordinate transformations) associated with those jobs.  That's definitely a much more complicated proposition.

Overall, it actually sounds like an idea that may be better implemented as a separate, though complimentary, plugin designed specifically for managing such a queue of jobs.

It's definitely an intriguing idea, which I'll keep in mind for possible implementation at some point.  However, I don't have much for free time at the moment, so it's not something I'd be likely to be able to take on anytime soon.

**Comment by maukcc** [comment]
Thanks for the feedback.
I see the seed has been planted :)
let me know when or if you are working on it, then I can test for you.
