### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Idus** [bradcfisher/OctoPrint-ExcludeRegionPlugin#32]
I was just asked by OctoPrint (v 1.4.0) today to do a Python 3 test (there is a new app for that) and report an issue to all plugin githubs that were found incompatible with Python 3 (if not already such an issue was stated).
Did the test and got back that the your plugin was Incompatible with Python 3 and could not find any other open issue about it - so here it is. :)

Cheers

**Comment by gvmturl** [comment]
any news?

**Comment by bradcfisher** [comment]
Things have been hectic lately, but I'll try to release a version with Python 3 support soon.  It's the top item on my priority list for this project.

**Comment by ekr1** [comment]
Yeah, don't worry. Thanks for the feedback - real_life™ has priority!

**Comment by nxvash** [comment]
any update on this?

**Comment by Hypertoken** [comment]
Did you upgrade to python 3 before checking all your add-ons compatibility? I did! For this add-on use the Python3 branch until official release (probably has bugs, but works in my setup). 

From terminal run; 
~/oprint/bin/pip install -U "https://github.com/bradcfisher/OctoPrint-ExcludeRegionPlugin/archive/feature/python3_compat.zip"

**Comment by bradcfisher** [comment]
A new version 0.3.0 with Python 3 support has been released
