### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by Brebinator** [bradcfisher/OctoPrint-ExcludeRegionPlugin#36]
Ocotoprint will no longer support previous versions of python in the near future, it would be awesome if this plugin could get updated to be compatible with python 3.6.

**Comment by MrPaulAR** [comment]
Duplicate of #32

**Comment by bradcfisher** [comment]
Thanks for the report.  I haven't had much time for side projects lately, but I'll try to work through the updates needed to ensure Python 3 compatibility soon.  Since Python 3 support is already requested under #32, I'll close this report as a dup.
