### ISSUE TITLE
Feature Request: Rotating/stretchable Regions 

### ISSUE THREAD

**Issue by GrubbyZebra** [bradcfisher/OctoPrint-ExcludeRegionPlugin#40]
For oddly shaped prints or prints on angles, it would be nice to be able to rotate the rectangular regions and make stretch the circles into ellipses. Not sure how much working this would actually be, but figured I'd throw it out there.

**Comment by bradcfisher** [comment]
@GrubbyZebra Thank you for the suggestion, and sorry for the delayed response.

Skewed rectangles and ellipses are more complicated from a geometric perspective and would be quite a bit more complicated to implement.  While it may be nice to have more options for how regions are defined, I do not anticipate adding additional capabilities like that in the near future.  That said, I do have plans to improve the underlying gcode processing in a way which should move things one step closer to being able to more easily support similar features, such as defining arbitrary polygonal regions.

Closing this for now, but I will keep the idea in mind.
