### ISSUE TITLE
Incompatible with OctoPrint Version 1.4.2 on Octopi 0.18.

### ISSUE THREAD

**Issue by Hooch180** [bradcfisher/OctoPrint-ExcludeRegionPlugin#54]
Hi,
I can't install this plugin using newest version of OctoPrint.
My version:
OctoPrint: Version 1.4.2
OctoPi: Version 0.18.0, running on Raspberry Pi 4 Model B Rev 1.4

![image](https://user-images.githubusercontent.com/1290823/98486417-7529c600-221d-11eb-829d-925a8fb8c56c.png)

**Comment by chunter1** [comment]
Same issue here with:
OctoPrint: Version 1.4.2
OctoPi: Version 0.17.0, running on Raspberry Pi 3 Model B Rev 1.2

**Comment by bradcfisher** [comment]
A new version 0.3.0 with Python 3 support has been released
