### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by katiekloss** [bradcfisher/OctoPrint-ExcludeRegionPlugin#67]
Hi! It doesn't appear that this plugin has been actively maintained for several years ( #64 has been open for a while and the plugin doesn't install in its current state because of it).

I'm willing to take ownership of it, is that okay?

**Comment by lmerega** [comment]
Hallo, if you will become the new owner, please note that there is a little issue.
This plugin does not work on Windows environment.
You have to use: https://github.com/jaketri/OctoPrint-ExcludeRegionPlugin/

The difference is only in:
OctoPrint-ExcludeRegionPlugin-master\octoprint_excluderegion\ExcludeRegionState.py

From:
from collections import OrderedDict, Mapping
To:
from collections import OrderedDict
from collections.abc import Mapping

This is to make the plugin compliant with Python 3.10.
